# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 02:43
from __future__ import unicode_literals

import csv
import os

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def load_data(apps, schema_editor):
    new_employee_roles = []
    employee_role_class = apps.get_model("back_office", "EmployeeRole")

    del schema_editor

    with open(os.path.join(settings.BASE_DIR, "var/csv/back_office_0002_initialData-employee_roles.csv")) as file:
        content = csv.DictReader(file, delimiter='|')

        for row in content:
            employee_role = employee_role_class(name=row['name'], description=row['description'])
            new_employee_roles.append(employee_role)

    employee_role_class.objects.bulk_create(new_employee_roles)


class Migration(migrations.Migration):
    replaces = [('back_office', '0001_initial'), ('back_office', '0002_employee_roles'),
                ('back_office', '0003_auto_20160228_1932'), ('back_office', '0004_auto_20160228_1933'),
                ('back_office', '0005_auto_20160228_1943'), ('back_office', '0006_auto_20160228_1944'),
                ('back_office', '0007_auto_20160228_1946'), ('back_office', '0008_auto_20160228_2211'),
                ('back_office', '0009_auto_20160228_2213')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_number', models.CharField(blank=True, max_length=5)),
                ('exterior_number', models.CharField(blank=True, max_length=5)),
                ('street', models.CharField(blank=True, max_length=45)),
                ('town', models.CharField(blank=True, max_length=45)),
                ('city', models.CharField(blank=True, max_length=45)),
                ('state', models.CharField(blank=True, max_length=45)),
                ('country', models.CharField(blank=True, max_length=45)),
                ('zip_code', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_since', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('number', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('seniority', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('website', models.URLField(blank=True, max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('picture', models.ImageField(upload_to='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Address')),
                ('contact',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('paternal_last_name', models.CharField(max_length=20)),
                ('maternal_last_name', models.CharField(max_length=20)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')])),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('picture', models.ImageField(upload_to='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Address')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.PersonProfile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.EmployeeRole'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.OrganizationProfile'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrated_branches',
                                    to='back_office.Employee'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='employees',
            field=models.ManyToManyField(to='back_office.Employee'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.OrganizationProfile'),
        ),
        migrations.RunPython(
            code=load_data,
        ),
        migrations.AlterField(
            model_name='address',
            name='exterior_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='interior_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='back_office.PersonProfile'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='back_office.Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='back_office.Address'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='back_office.PersonProfile'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='employees',
            field=models.ManyToManyField(blank=True, to='back_office.Employee'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='back_office.OrganizationProfile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='back_office.OrganizationProfile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back_office.PersonProfile'),
        ),
    ]
