# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 02:37
from __future__ import unicode_literals

import os

from django.db import migrations
import csv
from django.conf import settings


def load_data(apps, schema_editor):
    new_employee_roles = []
    employee_role_class = apps.get_model("back_office", "EmployeeRole")

    del schema_editor

    with open(os.path.join(settings.BASE_DIR, "var/csv/back_office_0002_initialData-employee_roles.csv")) as file:
        content = csv.DictReader(file, delimiter='|')

        for row in content:
            employee_role = employee_role_class(name=row['name'], description=row['description'])
            new_employee_roles.append(employee_role)

    employee_role_class.objects.bulk_create(new_employee_roles)


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
