# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0002_load_employee_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(to='back_office.EmployeeRole', verbose_name='roles'),
        ),
    ]
