# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0002_employee_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='exterior_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='interior_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
