# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 04:49
from __future__ import unicode_literals

import utils.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0002_load_employee_roles'),
    ]

    operations = [
        migrations.RunPython(utils.migrations.load_branch_offices)
    ]
