# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 05:56
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0002_load_employee_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='contact',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'dirección', 'verbose_name_plural': 'direcciones'},
        ),
        migrations.AlterModelOptions(
            name='branchoffice',
            options={'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterModelOptions(
            name='employeerole',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='personprofile',
            options={'verbose_name': 'perfil individual', 'verbose_name_plural': 'perfiles individuales'},
        ),
        migrations.RemoveField(
            model_name='branchoffice',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile',
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address', verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido.')], verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='name',
            field=models.CharField(default='', max_length=45, verbose_name='nombre de la sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El número telefónico debe ingresarse con el formato: '+999999999'. Se permiten hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='website',
            field=models.URLField(blank=True, max_length=45, validators=[django.core.validators.URLValidator(message='URL inválida.')], verbose_name='sitio web'),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address', verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido.')], verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=45, verbose_name='nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El número telefónico debe ingresarse con el formato: '+999999999'. Se permiten hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, max_length=45, validators=[django.core.validators.URLValidator(message='URL inválida.')], verbose_name='sitio web'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=45, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=45, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='address',
            name='exterior_number',
            field=models.CharField(max_length=10, verbose_name='número exterior'),
        ),
        migrations.AlterField(
            model_name='address',
            name='interior_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='número interior'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=45, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=45, verbose_name='calle'),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(blank=True, max_length=45, verbose_name='municipio'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrated_branches', to='back_office.Employee', verbose_name='administrador de la sucursal'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='employees',
            field=models.ManyToManyField(blank=True, to='back_office.Employee', verbose_name='empleados de la sucursal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_since',
            field=models.DateField(auto_now_add=True, verbose_name='antigüedad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back_office.PersonProfile', verbose_name='datos del empleado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.EmployeeRole', verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='seniority',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='antigüedad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario del sistema'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='description',
            field=models.CharField(max_length=50, verbose_name='descripción del rol'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='nombre del rol'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address', verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido.')], verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], verbose_name='género'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='maternal_last_name',
            field=models.CharField(max_length=20, verbose_name='apellido materno'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='name',
            field=models.CharField(max_length=20, verbose_name='nombre(s)'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='paternal_last_name',
            field=models.CharField(max_length=20, verbose_name='apellido paterno'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El número telefónico debe ingresarse con el formato: '+999999999'. Se permiten hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagen de perfil'),
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
    ]
