# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0002_load_employee_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='exterior_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=45),
        ),
    ]
