# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 05:16
from __future__ import unicode_literals
import utils.migrations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0003_load_branch_offices'),
    ]

    operations = [
        migrations.RunPython(utils.migrations.load_employees)
    ]
