# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 06:30
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0003_auto_20160304_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address', verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido.')], verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], default=0, verbose_name='género'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='maternal_last_name',
            field=models.CharField(default='', max_length=20, verbose_name='apellido materno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='nombre(s)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='paternal_last_name',
            field=models.CharField(default='', max_length=20, verbose_name='apellido paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El número telefónico debe ingresarse con el formato: '+999999999'. Se permiten hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagen de perfil'),
        ),
        migrations.DeleteModel(
            name='PersonProfile',
        ),
    ]
