# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 03:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0003_auto_20160301_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}')]),
        ),
    ]
