# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0003_auto_20160228_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.PersonProfile'),
        ),
    ]
