# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0004_auto_20160228_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
