# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0004_load_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'ciudad', 'verbose_name_plural': 'ciudades'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'país', 'verbose_name_plural': 'paises'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'región', 'verbose_name_plural': 'regiones'},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([]),
        ),
    ]
