# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0005_auto_20160228_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back_office.Address'),
        ),
    ]
