# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0007_auto_20160228_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='employees',
            field=models.ManyToManyField(blank=True, to='back_office.Employee'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back_office.OrganizationProfile'),
        ),
    ]
