# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0007_auto_20160526_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='foos',
            new_name='roles',
        ),
    ]
