# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0008_auto_20160228_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='back_office.OrganizationProfile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back_office.PersonProfile'),
        ),
    ]
