# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 04:04
from __future__ import unicode_literals

from django.db import migrations

from utils import migrations as utils_migrations


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(utils_migrations.load_employee_groups),
        migrations.RunPython(utils_migrations.load_branch_offices),
        migrations.RunPython(utils_migrations.load_employees),
        migrations.RunPython(utils_migrations.load_employee_groups_relationships),
        migrations.RunPython(utils_migrations.load_branch_employee_relationship),
        migrations.RunPython(utils_migrations.load_group_permissions),
    ]
