# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventories', 'load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_scrap',
            field=models.BooleanField(default=False, editable=False, verbose_name='es pedacería'),
        ),
    ]
