# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 23:26
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField(verbose_name='fecha de adquisición')),
                ('authorized_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumables_authorized',
                                   to='back_office.Employee', verbose_name='autorizado por')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee',
                                            verbose_name='comprador')),
            ],
            options={
                'verbose_name': 'consumible concreto',
                'verbose_name_plural': 'consumibles concretos',
            },
        ),
        migrations.CreateModel(
            name='ConsumableDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('description', models.CharField(max_length=50, verbose_name='descripción')),
                ('image', models.ImageField(upload_to='', verbose_name='imagen')),
                ('brand', models.CharField(max_length=45, verbose_name='marca')),
                ('model', models.CharField(max_length=45, verbose_name='modelo')),
                ('prefix', models.SmallIntegerField(blank=True,
                                                    choices=[(0, 'N/A'), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'),
                                                             (-12, 'p'), (-9, 'n'), (-6, 'μ'), (-3, 'm'), (-2, 'c'),
                                                             (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'),
                                                             (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'),
                                                             (24, 'Y')], default=0, verbose_name='prefijo de unidad')),
                ('unit', models.PositiveSmallIntegerField(
                    choices=[(0, 'N/A'), (1, 'm'), (2, 'in'), (3, 'ft'), (4, 'yd'), (5, 'mi'), (6, 'g'), (7, 's'),
                             (8, 'pz'), (9, 'l')], default=0, verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'consumible',
                'verbose_name_plural': 'consumibles',
            },
        ),
        migrations.CreateModel(
            name='ConsumableInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('consumable',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ConsumableDefinition',
                                   verbose_name='consumible')),
            ],
            options={
                'verbose_name': 'elemento de inventario',
                'verbose_name_plural': 'elementos de inventario',
            },
        ),
        migrations.CreateModel(
            name='ConsumablesInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.BranchOffice',
                                             verbose_name='sucursal')),
                ('items', models.ManyToManyField(blank=True, to='inventories.ConsumableInventoryItem',
                                                 verbose_name='consumibles')),
                ('last_updater',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee',
                                   verbose_name='autor de la última actualización')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='consumables_inventories_supervised',
                                                 to='back_office.Employee', verbose_name='supervisor')),
            ],
            options={
                'verbose_name': 'inventario de consumibles',
                'verbose_name_plural': 'inventarios de consumibles',
            },
        ),
        migrations.CreateModel(
            name='DurableGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField(verbose_name='fecha de adquisición')),
                ('authorized_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='durable_goods_authorized',
                                   to='back_office.Employee', verbose_name='autorizado por')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee',
                                            verbose_name='comprador')),
            ],
            options={
                'verbose_name': 'activo concreto',
                'verbose_name_plural': 'activos concretos',
            },
        ),
        migrations.CreateModel(
            name='DurableGoodDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('description', models.CharField(max_length=50, verbose_name='descripción')),
                ('image', models.ImageField(upload_to='', verbose_name='imagen')),
                ('brand', models.CharField(max_length=45, verbose_name='marca')),
                ('model', models.CharField(max_length=45, verbose_name='modelo')),
                ('prefix', models.SmallIntegerField(
                    choices=[(0, 'N/A'), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'), (-12, 'p'), (-9, 'n'),
                             (-6, 'μ'), (-3, 'm'), (-2, 'c'), (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'),
                             (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'), (24, 'Y')], default=0,
                    verbose_name='prefijo de la unidad')),
                ('unit', models.PositiveSmallIntegerField(
                    choices=[(0, 'N/A'), (1, 'm'), (2, 'in'), (3, 'ft'), (4, 'yd'), (5, 'mi'), (6, 'g'), (7, 's'),
                             (8, 'pz'), (9, 'l')], default=0, verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
            },
        ),
        migrations.CreateModel(
            name='DurableGoodInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('durable_good',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.DurableGoodDefinition',
                                   verbose_name='activo')),
            ],
            options={
                'verbose_name': 'elemento de inventario',
                'verbose_name_plural': 'elementos de inventarios',
            },
        ),
        migrations.CreateModel(
            name='DurableGoodsInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.BranchOffice',
                                             verbose_name='sucursal')),
                ('items',
                 models.ManyToManyField(blank=True, to='inventories.DurableGoodInventoryItem', verbose_name='activos')),
                ('last_updater',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee',
                                   verbose_name='autor de la última actualización')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='durable_goods_inventories_supervised',
                                                 to='back_office.Employee', verbose_name='supervisor')),
            ],
            options={
                'verbose_name': 'inventario de activos',
                'verbose_name_plural': 'inventarios de activos',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(
                    choices=[(0, 'En almacén'), (1, 'Parte de un producto'), (2, 'Devuelto'), (3, 'Destruido')],
                    verbose_name='estado')),
                ('acquisition_date',
                 models.DateField(default=django.utils.timezone.now, verbose_name='fecha de adquisición')),
                ('authorized_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_authorized',
                                   to='back_office.Employee', verbose_name='autorizado por')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee',
                                            verbose_name='comprador')),
            ],
            options={
                'verbose_name': 'material concreto',
                'verbose_name_plural': 'materiales concretos',
            },
        ),
        migrations.CreateModel(
            name='MaterialDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('description', models.CharField(max_length=50, verbose_name='descripción')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='imagen')),
                ('color', models.CharField(default='color', max_length=10)),
                ('length', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='longitud')),
                ('width', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='anchura')),
                ('thickness', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='grosor')),
                ('weight', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='peso')),
                ('prefix', models.SmallIntegerField(blank=True,
                                                    choices=[(0, 'N/A'), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'),
                                                             (-12, 'p'), (-9, 'n'), (-6, 'μ'), (-3, 'm'), (-2, 'c'),
                                                             (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'),
                                                             (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'),
                                                             (24, 'Y')], default=0, verbose_name='prefijo de unidad')),
                ('unit', models.PositiveSmallIntegerField(
                    choices=[(0, 'N/A'), (1, 'm'), (2, 'in'), (3, 'ft'), (4, 'yd'), (5, 'mi'), (6, 'g'), (7, 's'),
                             (8, 'pz'), (9, 'l')], default=0, verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='MaterialInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('material',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.MaterialDefinition',
                                   verbose_name='material')),
            ],
            options={
                'verbose_name': 'elemento de inventario',
                'verbose_name_plural': 'elementos de inventario',
            },
        ),
        migrations.CreateModel(
            name='MaterialsInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.BranchOffice',
                                             verbose_name='sucursal')),
                ('items',
                 models.ManyToManyField(blank=True, to='inventories.MaterialInventoryItem', verbose_name='materiales')),
                ('last_updater',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee',
                                   verbose_name='autor de la última actualización')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='materials_inventories_supervised',
                                                 to='back_office.Employee', verbose_name='supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(
                    choices=[(0, 'En producción'), (1, 'En almacén'), (2, 'Vendido'), (3, 'Devuelto'),
                             (4, 'Destruido')], verbose_name='estado')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='fecha de manufactura')),
            ],
            options={
                'verbose_name': 'producto concreto',
                'verbose_name_plural': 'productos concretos',
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('prefix', models.SmallIntegerField(blank=True,
                                                    choices=[(0, 'N/A'), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'),
                                                             (-12, 'p'), (-9, 'n'), (-6, 'μ'), (-3, 'm'), (-2, 'c'),
                                                             (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'),
                                                             (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'),
                                                             (24, 'Y')], default=0, verbose_name='prefijo de unidad')),
                ('unit', models.PositiveSmallIntegerField(
                    choices=[(0, 'N/A'), (1, 'm'), (2, 'in'), (3, 'ft'), (4, 'yd'), (5, 'mi'), (6, 'g'), (7, 's'),
                             (8, 'pz'), (9, 'l')], default=0, verbose_name='unidad')),
                ('required_units',
                 models.PositiveSmallIntegerField(default=1, verbose_name='unidades requeridas del componente')),
                ('required_amount_per_unit',
                 models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='cantidad por unidad')),
                ('material',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.MaterialDefinition',
                                   verbose_name='material')),
            ],
            options={
                'verbose_name': 'componente de un producto',
                'verbose_name_plural': 'componentes de productos',
            },
        ),
        migrations.CreateModel(
            name='ProductDefinition',
            fields=[
                ('sku', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='SKU')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='descripción')),
                ('short_description', models.CharField(blank=True, max_length=50, verbose_name='descripción corta')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='imagen')),
                ('color', models.CharField(blank=True, max_length=10, verbose_name='color')),
                ('length', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='longitud')),
                ('width', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='anchura')),
                ('thickness', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='grosor')),
                ('weight', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='peso')),
                ('is_composite', models.BooleanField(default=False, verbose_name='es compuesto')),
                ('prefix', models.SmallIntegerField(blank=True,
                                                    choices=[(0, 'N/A'), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'),
                                                             (-12, 'p'), (-9, 'n'), (-6, 'μ'), (-3, 'm'), (-2, 'c'),
                                                             (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'),
                                                             (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'),
                                                             (24, 'Y')], default=0, verbose_name='prefijo de unidad')),
                ('unit', models.PositiveSmallIntegerField(
                    choices=[(0, 'N/A'), (1, 'm'), (2, 'in'), (3, 'ft'), (4, 'yd'), (5, 'mi'), (6, 'g'), (7, 's'),
                             (8, 'pz'), (9, 'l')], default=0, verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ProductDefinition',
                                   verbose_name='producto')),
            ],
            options={
                'verbose_name': 'elemento de inventario',
                'verbose_name_plural': 'elementos de inventarios',
            },
        ),
        migrations.CreateModel(
            name='ProductsInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.BranchOffice',
                                             verbose_name='sucursal')),
                ('items',
                 models.ManyToManyField(blank=True, to='inventories.ProductInventoryItem', verbose_name='productos')),
                ('last_updater',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee',
                                   verbose_name='autor de la última actualización')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='products_inventories_supervised',
                                                 to='back_office.Employee', verbose_name='supervisor')),
            ],
            options={
                'verbose_name': 'inventario de productos',
                'verbose_name_plural': 'inventarios de productos',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_datetime',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de autorización')),
                ('authorized_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee',
                                   verbose_name='autorizado por')),
                ('product_definition',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ProductDefinition',
                                   verbose_name='producto')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'órdenes de trabajo',
            },
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ProductDefinition',
                                    verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ProductDefinition',
                                    verbose_name='definición'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='back_office.Employee', verbose_name='manufacturado por'),
        ),
        migrations.AddField(
            model_name='material',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.MaterialDefinition',
                                    verbose_name='definición'),
        ),
        migrations.AddField(
            model_name='durablegood',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.DurableGoodDefinition',
                                    verbose_name='definición'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ConsumableDefinition',
                                    verbose_name='definición'),
        ),
    ]
