# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_auto_20161027_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='are_products_received',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Confirmado'), (1, 'Cancelado'), (2, 'Pendiente'), (3, 'Completa')], default=2, verbose_name='estado'),
        ),
    ]
