# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdefinition',
            name='prefix',
            field=models.SmallIntegerField(blank=True, choices=[(0, ''), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'), (-12, 'p'), (-9, 'n'), (-6, 'μ'), (-3, 'm'), (-2, 'c'), (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'), (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'), (24, 'Y')], default=0),
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='prefix',
            field=models.SmallIntegerField(blank=True, choices=[(0, ''), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'), (-12, 'p'), (-9, 'n'), (-6, 'μ'), (-3, 'm'), (-2, 'c'), (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'), (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'), (24, 'Y')], default=0),
        ),
        migrations.AddField(
            model_name='productdefinition',
            name='prefix',
            field=models.SmallIntegerField(blank=True, choices=[(0, ''), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'), (-12, 'p'), (-9, 'n'), (-6, 'μ'), (-3, 'm'), (-2, 'c'), (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'), (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'), (24, 'Y')], default=0),
        ),
        migrations.AlterField(
            model_name='consumabledefinition',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'm'), (1, 'in'), (2, 'ft'), (3, 'yd'), (4, 'mi'), (5, 'g'), (6, 's'), (7, 'pz'), (8, 'l')]),
        ),
        migrations.AlterField(
            model_name='durablegooddefinition',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'm'), (1, 'in'), (2, 'ft'), (3, 'yd'), (4, 'mi'), (5, 'g'), (6, 's'), (7, 'pz'), (8, 'l')]),
        ),
        migrations.AlterField(
            model_name='material',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'En almacén'), (1, 'Parte de un producto'), (2, 'Devuelto'), (3, 'Destruido')]),
        ),
        migrations.AlterField(
            model_name='materialdefinition',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'm'), (1, 'in'), (2, 'ft'), (3, 'yd'), (4, 'mi'), (5, 'g'), (6, 's'), (7, 'pz'), (8, 'l')]),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'm'), (1, 'in'), (2, 'ft'), (3, 'yd'), (4, 'mi'), (5, 'g'), (6, 's'), (7, 'pz'), (8, 'l')]),
        ),
        migrations.AlterField(
            model_name='productdefinition',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'm'), (1, 'in'), (2, 'ft'), (3, 'yd'), (4, 'mi'), (5, 'g'), (6, 's'), (7, 'pz'), (8, 'l')]),
        ),
    ]
