# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_load_product_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttransfer',
            options={'verbose_name': 'transferencia de productos', 'verbose_name_plural': 'transferencias de productos'},
        ),
    ]
