# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', 'load_initial_data'),
        ('inventories', '0002_auto_20161018_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentry',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='productentry',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Confirmado'), (1, 'Cancelado'), (2, 'Pendiente')], default=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch_office',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='back_office.BranchOffice', verbose_name='sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Confirmado'), (1, 'Cancelado'), (2, 'Pendiente')], default=2, verbose_name='estado'),
        ),
    ]
