# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20160228_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumabledefinition',
            name='prefix',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'N/A'), (-24, 'y'), (-21, 'z'), (-18, 'a'), (-15, 'f'), (-12, 'p'), (-9, 'n'), (-6, 'μ'), (-3, 'm'), (-2, 'c'), (-1, 'd'), (1, 'da'), (2, 'h'), (3, 'k'), (6, 'M'), (9, 'G'), (12, 'T'), (15, 'P'), (18, 'E'), (21, 'Z'), (24, 'Y')], default=0),
        ),
    ]
