# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20160403_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='authorized_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumables_authorized', to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
        ),
        migrations.AlterField(
            model_name='material',
            name='authorized_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials_authorized', to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
        ),
    ]
