# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_consumabledefinition_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.Consumable'),
        ),
        migrations.AddField(
            model_name='movement',
            name='durable_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.DurableGood'),
        ),
        migrations.AddField(
            model_name='movement',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.Material'),
        ),
        migrations.AddField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.Product'),
        ),
        migrations.AlterField(
            model_name='consumablesinventory',
            name='items',
            field=models.ManyToManyField(blank=True, to='inventories.ConsumableInventoryItem'),
        ),
        migrations.AlterField(
            model_name='durablegoodsinventory',
            name='items',
            field=models.ManyToManyField(blank=True, to='inventories.DurableGoodInventoryItem'),
        ),
        migrations.AlterField(
            model_name='materialsinventory',
            name='items',
            field=models.ManyToManyField(blank=True, to='inventories.MaterialInventoryItem'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Producto'), (1, 'Material'), (2, 'Empleado'), (3, 'Consumible'), (4, 'Recurso')]),
        ),
        migrations.AlterField(
            model_name='productsinventory',
            name='items',
            field=models.ManyToManyField(blank=True, to='inventories.ProductInventoryItem'),
        ),
    ]
