# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20160403_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='durablegooddefinition',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagen'),
        ),
    ]
