# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventories', '0005_auto_20160618_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransfer',
            name='rejection_reason',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(0, 'La cantidad recibida no concuerda con la esperada.'),
                                                            (1, 'El material recibido no concuerda con el esperado.'),
                                                            (1, 'El material se encuentra en mal estado.')], null=True,
                                                   verbose_name='motivo de rechazo'),
        ),
    ]
