# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventories', '0006_auto_20160618_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransfer',
            name='transfer_has_been_made',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
