# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_auto_20160403_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdefinition',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
    ]
