# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0007_auto_20160403_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomponent',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='productcomponent',
            name='unit',
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='required_amount_per_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='cantidad requerida por unidad'),
        ),
    ]
