# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 19:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventories', '0007_producttransfer_transfer_has_been_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangedproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='exchangedproduct',
            name='reimbursement',
        ),
        migrations.RemoveField(
            model_name='productreimbursement',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='productreimbursement',
            name='from_branch',
        ),
        migrations.AddField(
            model_name='productreimbursement',
            name='inventory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT,
                                    to='inventories.ProductsInventory', verbose_name='inventario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExchangedProduct',
        ),
    ]
