# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_auto_20160403_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='product_definition',
        ),
        migrations.AlterModelOptions(
            name='materialsinventory',
            options={'verbose_name': 'inventario de materiales', 'verbose_name_plural': 'inventarios de materiales'},
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
