# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_auto_20160626_1548'),
        ('inventories', '0009_productreimbursement_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransfer',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finances.Sale'),
            preserve_default=False,
        ),
    ]
