# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_producttransfer_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransfer',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.Sale', verbose_name='venta cancelada relacionada'),
        ),
    ]
