# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 04:07
from __future__ import unicode_literals

from django.db import migrations

from utils import migrations as utils_migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inventories', '0002_auto_20161020_2349'),
    ]

    operations = [
        migrations.RunPython(utils_migrations.load_products_inventory)
    ]
