# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 05:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('back_office', '0001_initial'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.Client')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEstimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.Employee')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEstimationMaterialsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.MaterialDefinition')),
                ('project_estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.ProjectEstimation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEstimationProductsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.ProductDefinition')),
                ('project_estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.ProjectEstimation')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(max_length=300)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_repairs', to='back_office.Employee')),
                ('durable_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.DurableGoodDefinition')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_repairs', to='back_office.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.Client')),
            ],
        ),
    ]
