# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='product_definition',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
