# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
    ]
