# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20160321_1158'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='transactions',
            field=models.ManyToManyField(to='finances.Transaction', verbose_name='transacciones'),
        ),
    ]
