# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_project_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='costo'),
        ),
    ]
