# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_auto_20160228_2320'),
        ('operations', '0002_auto_20160228_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEstimationMaterialsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.MaterialDefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEstimationProductsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.ProductDefinition')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='products',
        ),
        migrations.AddField(
            model_name='projectestimationproductsentry',
            name='project_estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.ProjectEstimation'),
        ),
        migrations.AddField(
            model_name='projectestimationmaterialsentry',
            name='project_estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.ProjectEstimation'),
        ),
    ]
