# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20160318_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost',
        ),
    ]
