# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0002_load_employee_roles'),
        ('operations', '0002_auto_20160313_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('position', geoposition.fields.GeopositionField(max_length=42, verbose_name='localización')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee', verbose_name='empleado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'visita a proyecto',
                'verbose_name_plural': 'visitas a proyecto',
            },
        ),
    ]
