# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_project_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='costo'),
        ),
        migrations.AlterField(
            model_name='projectmaterialsentry',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='projectproductsentry',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='cantidad'),
        ),
    ]
