# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20160321_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_repairs', to=settings.AUTH_USER_MODEL, verbose_name='autorizada por'),
        ),
    ]
