# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0009_auto_20160403_1818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0007_auto_20160403_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('authorization_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de autorización')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autorizado por')),
                ('product_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ProductDefinition', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'órdenes de trabajo',
            },
        ),
    ]
