# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', 'load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='chofer'),
        ),
    ]
