# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 02:43
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='archivo')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('is_closed', models.BooleanField(default=False, verbose_name='cerrada')),
            ],
            options={
                'verbose_name_plural': 'facturas',
                'verbose_name': 'factura',
            },
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo')),
            ],
            options={
                'verbose_name_plural': 'costos de materiales',
                'verbose_name': 'costo de un material',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Solicitada'), (1, 'En progreso'), (2, 'Completa'), (3, 'Entregada'), (4, 'Cancelada'), (5, 'Devuelta')], default=0, verbose_name='estado')),
                ('target', models.PositiveSmallIntegerField(choices=[(0, 'Proyecto'), (1, 'Productos'), (2, 'Servicios'), (3, 'Productos y servicios'), (4, 'Todos')], verbose_name='entregable')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='subtotal')),
                ('shipping_and_handling', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='manejo y envío')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='descuento')),
            ],
            options={
                'verbose_name_plural': 'órdenes',
                'verbose_name': 'orden',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
            ],
            options={
                'verbose_name_plural': 'productos de órdenes',
                'verbose_name': 'productos de una orden',
            },
        ),
        migrations.CreateModel(
            name='OrderServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'servicios de órdenes',
                'verbose_name': 'servicios de una orden',
            },
        ),
        migrations.CreateModel(
            name='ProductInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'facturas de producto',
                'verbose_name': 'factura de producto',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
            ],
            options={
                'verbose_name_plural': 'precios de productos',
                'verbose_name': 'precio de producto',
            },
        ),
        migrations.CreateModel(
            name='RepairCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo')),
            ],
            options={
                'verbose_name_plural': 'costos de reparaciones',
                'verbose_name': 'costo de una reparación',
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Invoice', verbose_name='factura')),
            ],
            options={
                'verbose_name_plural': 'servicios de facturas',
                'verbose_name': 'servicio de una factura',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.Invoice', verbose_name='factura')),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Client', verbose_name='pagado por')),
            ],
            options={
                'verbose_name_plural': 'transacciones',
                'verbose_name': 'transacción',
            },
        ),
    ]
