# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
        ('operations', '0001_initial'),
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='número')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Solicitada'), (1, 'En progreso'), (2, 'Completa'), (3, 'Cancelada'), (4, 'Devuelta')], verbose_name='estado')),
                ('target', models.PositiveSmallIntegerField(choices=[(0, 'Productos'), (1, 'Servicios'), (2, 'Productos y servicios')], verbose_name='objeto')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='subtotal')),
                ('shipping_and_handling', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='manejo y envío')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='descuento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Client', verbose_name='cliente')),
            ],
            options={
                'verbose_name_plural': 'Órdenes',
                'verbose_name': 'Orden',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Order', verbose_name='orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.ProductDefinition', verbose_name='producto')),
            ],
        ),
        migrations.CreateModel(
            name='OrderServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RepairCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.Repair')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.Invoice')),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Client')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Order'),
        ),
    ]
