# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='folio externo')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='archivo')),
                ('is_closed', models.BooleanField(default=False, verbose_name='cerrada')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Válida'), (1, 'Venta'), (2, 'Cancelada')], default=0, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo')),
            ],
            options={
                'verbose_name': 'costo de un material',
                'verbose_name_plural': 'costos de materiales',
            },
        ),
    ]
