# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', 'load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproductitem',
            name='special_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='longitud especial (m)'),
        ),
        migrations.AddField(
            model_name='saleproductitem',
            name='special_thickness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='grosor especial (mm)'),
        ),
        migrations.AddField(
            model_name='saleproductitem',
            name='special_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='anchura especial (m)'),
        ),
    ]
