# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 04:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'precio de producto', 'verbose_name_plural': 'precios de productos'},
        ),
        migrations.AlterField(
            model_name='productprice',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee', verbose_name='autorizado por'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.Product', verbose_name='producto'),
        ),
    ]
