# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Client', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_and_handling',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitada'), (1, 'En progreso'), (2, 'Completa'), (3, 'Cancelada'), (4, 'Devuelta')], verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Productos'), (1, 'Servicios'), (2, 'Productos y servicios')], verbose_name='objeto'),
        ),
    ]
