# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 00:11
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('inventories', '0001_initial'),
        ('back_office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('product',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='inventories.Product', verbose_name='producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
            ],
            options={
                'verbose_name': 'precio de producto',
                'verbose_name_plural': 'precios de productos',
            },
        ),
        migrations.CreateModel(
            name='RepairCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo')),
                ('authorized_by',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL,
                                   verbose_name='autorizado por')),
            ],
            options={
                'verbose_name': 'costo de una reparación',
                'verbose_name_plural': 'costos de reparaciones',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'En mostrador'), (1, 'Con entrega')], default=0,
                                                          verbose_name='tipo de venta')),
                ('state',
                 models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Activa'), (1, 'Cancelada')], default=0,
                                                  verbose_name='estado')),
                ('payment_method', models.PositiveSmallIntegerField(
                    choices=[(0, 'Efectivo'), (1, 'Transferencia'), (2, 'Contra entrega')], default=0,
                    verbose_name='método de pago')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('shipping_and_handling',
                 models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='manejo y envío')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descuento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Client',
                                             verbose_name='cliente')),
                ('inventory', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT,
                                                to='inventories.ProductsInventory', verbose_name='inventario')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Invoice',
                                              verbose_name='factura')),
                ('shipping_address',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   to='back_office.Address', verbose_name='dirección de envío')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='SaleProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('special_length',
                 models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='longitud especial (m)')),
                ('special_width',
                 models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='anchura especial (m)')),
                ('special_thickness',
                 models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='grosor especial (mm)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.Product',
                                              verbose_name='producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Sale',
                                           verbose_name='venta')),
            ],
            options={
                'verbose_name': 'producto de la venta',
                'verbose_name_plural': 'productos de la venta',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.Invoice',
                                              verbose_name='factura')),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Client',
                                               verbose_name='pagado por')),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to='finances.Transaction', verbose_name='transacción'),
        ),
    ]
