# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcost',
            options={'verbose_name': 'costo de un material', 'verbose_name_plural': 'costos de materiales'},
        ),
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name': 'productos de una orden', 'verbose_name_plural': 'productos de órdenes'},
        ),
        migrations.AlterModelOptions(
            name='orderservices',
            options={'verbose_name': 'servicios de una orden', 'verbose_name_plural': 'servicios de órdenes'},
        ),
        migrations.AlterModelOptions(
            name='repaircost',
            options={'verbose_name': 'costo de una reparación', 'verbose_name_plural': 'costos de reparaciones'},
        ),
        migrations.AlterModelOptions(
            name='serviceinvoice',
            options={'verbose_name': 'servicio de una factura', 'verbose_name_plural': 'servicios de facturas'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transacción', 'verbose_name_plural': 'transacciones'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='materialcost',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Employee', verbose_name='autorizado por'),
        ),
        migrations.AlterField(
            model_name='materialcost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo'),
        ),
        migrations.AlterField(
            model_name='materialcost',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Order', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Service', verbose_name='servicio'),
        ),
        migrations.AlterField(
            model_name='repaircost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo'),
        ),
        migrations.AlterField(
            model_name='repaircost',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.Repair', verbose_name='reparación'),
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Invoice', verbose_name='factura'),
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Service', verbose_name='servicio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.Invoice', verbose_name='factura'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_office.Client', verbose_name='pagado por'),
        ),
    ]
