# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
