# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'factura', 'verbose_name_plural': 'facturas'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'orden', 'verbose_name_plural': 'órdenes'},
        ),
        migrations.AlterModelOptions(
            name='productinvoice',
            options={'verbose_name': 'factura de producto', 'verbose_name_plural': 'facturas de producto'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='cerrada'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Order', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitada'), (1, 'En progreso'), (2, 'Completa'), (3, 'Entregada'), (4, 'Cancelada'), (5, 'Devuelta')], verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='productinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Invoice', verbose_name='factura'),
        ),
        migrations.AlterField(
            model_name='productinvoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.Product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
