# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0002_auto_20160828_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventories', '0002_auto_20160828_1654'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaircost',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.Repair', verbose_name='reparación'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='authorized_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='authorized_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.Material', verbose_name='material'),
        ),
    ]
