# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 00:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
        ('finances', '0002_auto_20160814_1936'),
        ('inventories', '0002_auto_20160814_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaircost',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.Repair',
                                    verbose_name='reparación'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='authorized_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='authorized_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.Material',
                                       verbose_name='material'),
        ),
    ]
