# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20160228_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcost',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.Material'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.Product'),
        ),
    ]
