# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20160321_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcost',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.MaterialDefinition', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.ProductDefinition', verbose_name='producto'),
        ),
    ]
