# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0003_auto_20160528_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='monto'),
        ),
    ]
