# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0004_auto_20160403_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaircost',
            name='authorized_by',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialcost',
            name='authorized_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='authorized_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autorizado por'),
        ),
    ]
