# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20160528_1923'),
        ('finances', '0005_auto_20160611_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.Product', verbose_name='producto')),
            ],
            options={
                'verbose_name_plural': 'productos de la venta',
                'verbose_name': 'producto de la venta',
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='saleproductitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Sale', verbose_name='venta'),
        ),
    ]
