# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20160403_1638'),
        ('finances', '0005_auto_20160403_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Project', verbose_name='proyecto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Proyecto'), (1, 'Productos'), (2, 'Servicios'), (3, 'Productos y servicios'), (4, 'Todos')], verbose_name='objeto'),
        ),
    ]
