# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20160403_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitada'), (1, 'En progreso'), (2, 'Completa'), (3, 'Entregada'), (4, 'Cancelada'), (5, 'Devuelta')], default=0, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Proyecto'), (1, 'Productos'), (2, 'Servicios'), (3, 'Productos y servicios'), (4, 'Todos')], verbose_name='entregable'),
        ),
    ]
