# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20160528_1923'),
        ('finances', '0007_remove_sale_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproductitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleproductitem',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventories.Product', verbose_name='producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.DeleteModel(
            name='SaleProductItem',
        ),
    ]
