# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('finances', '0008_auto_20160618_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='project',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderservices',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderservices',
            name='service',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='order',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='descuento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Project', verbose_name='proyecto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_and_handling',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='manejo y envío'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitada'), (1, 'En progreso'), (2, 'Completa'), (3, 'Entregada'), (4, 'Cancelada'), (5, 'Devuelta')], default=0, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='sale',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Proyecto'), (1, 'Productos'), (2, 'Servicios'), (3, 'Productos y servicios'), (4, 'Todos')], default=0, verbose_name='entregable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
        migrations.DeleteModel(
            name='OrderServices',
        ),
    ]
