# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_auto_20160618_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='target',
        ),
    ]
