# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_remove_sale_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
    ]
