# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_auto_20160618_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de venta'),
        ),
    ]
