# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Efectivo'), (1, 'Transferencia'), (2, 'Contra entrega')], default=0, verbose_name='método de pago'),
        ),
    ]
