# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0014_auto_20160618_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rejection_reason',
            field=models.TextField(default=0, max_length=250, verbose_name='motivo de rechazo'),
            preserve_default=False,
        ),
    ]
