# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0015_transaction_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rejection_reason',
        ),
    ]
