# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_sale_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Válida'), (1, 'Cancelada')], default=0, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Válida'), (1, 'Cancelada')], default=0, verbose_name='estado'),
        ),
    ]
