# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0011_auto_20160626_1819'),
        ('finances', '0018_auto_20160626_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.Product', verbose_name='producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'producto de la venta',
                'verbose_name_plural': 'productos de la venta',
            },
        ),
    ]
