# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0020_auto_20160628_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='monto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='descuento'),
        ),
    ]
