# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0021_auto_20160628_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Activa'), (1, 'Cancelada')], default=0,
                                                   verbose_name='estado'),
        ),
    ]
