# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0023_sale_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Nueva'), (1, 'Válida'), (2, 'Cancelada')],
                                                   default=1, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto'),
        ),
    ]
