# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0024_auto_20160701_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Válida'), (1, 'Venta'), (2, 'Cancelada')], default=0,
                                                   verbose_name='estado'),
        ),
    ]
