# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 04:14
from __future__ import unicode_literals

from django.db import migrations

from utils import migrations as utils_migrations


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0003_auto_20160814_1936'),
        ('back_office', 'load_initial_data'),
        ('inventories', 'load_initial_data')
    ]

    operations = [
        migrations.RunPython(utils_migrations.load_product_prices)
    ]
